CREATE DATABASE comp_1006_200528741;
USE comp_1006_200528741;

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(200) NOT NULL UNIQUE KEY,
	password VARCHAR(256) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE carts (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cart_name VARCHAR(20),
    user_id INT NOT NULL,
    UNIQUE(cart_name, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
)ENGINE=InnoDB;

CREATE TABLE products (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(50) NOT NULL,
    price INT NOT NULL,
    description VARCHAR(200),
    cart_id INT NOT NULL,
    user_id INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id),
    FOREIGN KEY (cart_id) REFERENCES carts(id)
) ENGINE=InnoDB;